const freudianConcepts = [
    "Inconsciente",
    "Preconsciente",
    "Conciencia",
    "Ello (Id)",
    "Yo (Ego)",
    "Superyó (Superego)",
    "Pulsión de vida (Eros)",
    "Pulsión de muerte (Thanatos)",
    "Principio de placer",
    "Principio de realidad",
    "Represión",
    "Resistencia",
    "Transferencia",
    "Contratransferencia",
    "Líbido",
    "Narcisismo",
    "Complejo de Edipo",
    "Complejo de Castración",
    "Fase oral",
    "Fase anal",
    "Fase fálica",
    "Período de latencia",
    "Fase genital",
    "Sueño (Realización de deseos)",
    "Condensación",
    "Desplazamiento",
    "Acto fallido",
    "Chiste",
    "Síntoma",
    "Trauma",
    "Duelo",
    "Melancolía",
    "Sublimación",
    "Proyección",
    "Racionalización",
    "Negación",
    "Identificación",
    "Angustia",
    "Fantasía",
    "Recuerdo encubridor",
    "Compulsión de repetición",
    "Pulsión parcial",
    "Zona erógena",
    "Objeto de la pulsión",
    "Fin de la pulsión",
    "Fuente de la pulsión",
    "Histeria",
    "Neurosis obsesiva",
    "Fobia",
    "Perversión",
    "Psicosis",
    "Fetichismo",
    "Escisión del Yo",
    "Renegación (Verleugnung)"
];
